# Generated by Django 5.2.3 on 2025-06-18 18:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
